In [5]:
a = [1.0, 2.0, 1.0]

In [6]:
a

[1.0, 2.0, 1.0]

In [1]:
import torch
a = torch.ones(3)

In [8]:
a

tensor([1., 1., 1.])

In [9]:
a.item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [10]:
a[1]

tensor(1.)

In [11]:
a[1].item()

1.0

In [2]:
 torch.cuda.is_available()

True

In [3]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [4]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [6]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [7]:
points.shape

torch.Size([3, 2])

In [8]:
points[0, 1]

tensor(1.)

In [9]:
points[2, 1]

tensor(1.)

In [10]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [11]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [13]:
points[None].shape

torch.Size([1, 3, 2])

In [14]:
points.unsqueeze()

TypeError: unsqueeze() missing 1 required positional arguments: "dim"

In [15]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]

In [16]:
img_t

tensor([[[-0.0815, -1.3052,  1.0226, -0.3702, -2.4514],
         [-1.3329,  2.0680, -0.7625,  1.3305, -0.6604],
         [ 0.6849, -0.9808,  0.2743, -1.4298, -0.2924],
         [ 0.7820, -0.4091, -0.3711,  1.2274, -0.8565],
         [-1.0557,  1.3438,  0.4929,  1.1319, -1.1478]],

        [[-0.4135, -0.7646,  0.0725,  0.6966,  1.0213],
         [ 2.3792, -0.5415,  0.4434, -0.5106,  1.4335],
         [-1.5760,  1.5132, -0.2455, -1.8347,  0.9575],
         [-0.7767,  0.4126,  0.2517,  0.7306, -0.8703],
         [ 0.2831,  0.1096,  0.7307,  0.4061,  0.5799]],

        [[ 0.0550,  0.1309, -0.0823, -0.0484,  1.4487],
         [ 0.3921, -0.1991,  1.4334, -0.4046,  0.9707],
         [-0.5183,  1.0026, -1.4680,  0.5604, -0.6112],
         [-0.0923,  1.3265, -0.0779, -0.2411, -0.6946],
         [-0.4006,  1.0432, -0.3441, -0.2074,  0.9205]]])

In [17]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [18]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [19]:
batch_t.shape

torch.Size([2, 3, 5, 5])

In [20]:
img_t.shape

torch.Size([3, 5, 5])

In [21]:
img_gray_naive = img_t.mean(-3)

In [22]:
img_gray_naive.shape

torch.Size([5, 5])

In [23]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [24]:
unsqueezed_weights.shape

torch.Size([3, 1, 1])

In [26]:
weights.shape

torch.Size([3])

In [27]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [28]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


/home/yizhouw/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor.py:1240: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /opt/conda/conda-bld/pytorch_1712608843393/work/c10/core/TensorImpl.h:1921.)
  return super().refine_names(names)


In [41]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/tmp/ipykernel_325797/2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [45]:
points_storage = points.storage()
points_storage[0]

4.0

In [46]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [47]:
second_point.size()

torch.Size([2])

In [48]:
second_point

tensor([5., 3.])

In [49]:
second_point.size()

torch.Size([2])

In [51]:
test_point = points[0,1]

In [52]:
test_point

tensor(1.)

In [53]:
test_point.storage_offset()

1

In [54]:
test_point.size()

torch.Size([])

In [55]:
test_point.stride()

()

In [62]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
id(points.storage()) == id(points_t.storage())

True

In [63]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [64]:
points.storage_offset(), points_t.storage_offset()

(0, 0)

In [65]:
points.is_contiguous()

True

In [66]:
points_t.is_contiguous()

False

In [67]:
points_t_cont = points_t.contiguous()

In [68]:
id(points.storage()) == id(points_t_cont.storage())

True

In [69]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [70]:
points.is_contiguous()

True

In [71]:
id(points.storage()) == id(points_t.storage())

True

In [73]:
points, points_t, points_t_cont

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
 tensor([[4., 5., 2.],
         [1., 3., 1.]]),
 tensor([[4., 5., 2.],
         [1., 3., 1.]]))

In [74]:
points.stride(), points_t.stride(), points_t_cont.stride()

((2, 1), (1, 2), (3, 1))

In [76]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [77]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [78]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [83]:
id(points_t.storage()) == id(points_t_cont.storage())

True

In [84]:
points.stride()

(2, 1)

In [85]:
points_t.stride()

(1, 2)

In [86]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [87]:
points.is_contiguous()

True

In [88]:
points_t.is_contiguous()

False

In [89]:
points_t_cont.is_contiguous()

True

In [91]:
points_t, points_t.storage(), points_t.stride()

(tensor([[4., 5., 2.],
         [1., 3., 1.]]),
  4.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
 (1, 2))

In [92]:
points_t_cont, points_t_cont.storage(), points_t_cont.stride()

(tensor([[4., 5., 2.],
         [1., 3., 1.]]),
  4.0
  5.0
  2.0
  1.0
  3.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
 (3, 1))